# Be explicit about all rules. Hover on the rule in the editor to see it, or
# review: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
MD001: true
# MD002: Deprecated
MD003:
  style: atx
MD004:
  style: dash
MD005: true
# MD006: Deprecated
MD007:
  indent: 2
  start_indented: false
  start_indent: 2
MD009:
  br_spaces: 0
  list_item_empty_lines: false
  strict: true
MD010:
  code_blocks: true
  spaces_per_tab: 2
MD011: true
MD012:
  maximum: 1
MD013:
  line_length: 120
  heading_line_length: 80
  code_block_line_length: 80
  code_blocks: true
  tables: false
  headings: true
  headers: true
  strict: false
  stern: false
MD014: true
MD018: true
MD019: true
# MD020: Ignore, not using Closed-Atx Style Headings
# MD021: Ignore, not using Closed-Atx Style Headings
MD022:
  lines_above: 1
  lines_below: 1
MD023: true
MD024:
  allow_different_nesting: true
  siblings_only: false
MD025:
  level: 1
  front_matter_title: ^\s*title\s*[:=]
MD026:
  punctuation: .,;:!。，；：！
MD027: true
MD028: true
MD029:
  style: one
MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1
MD031:
  list_items: true
MD032: true
MD033: true
MD034: true
MD035:
  style: ---
MD036:
  punctuation: .,;:!?。，；：！？
MD037: true
MD038: true
MD039: true
MD040: true
MD041:
  level: 1
  front_matter_title: ^\s*title\s*[:=]
MD042: true
# MD043: No required heading structure for most files.
# MD044: Use Vale for capitalization, not MarkdownLint.
MD045: true
MD046:
  style: fenced
MD047: true
MD048:
  style: backtick
MD049:
  style: underscore
MD050:
  style: asterisk
MD051: true
MD052: true
MD053: true
