platen:
  theme:
    mode: auto
    variables:
      basic_scss:
        padding-minimal: 1px
        padding-small: 0.25rem
        padding-medium: 0.5rem
        padding-large: 1rem
        font-size-base: 16px
        font-size-small: 0.75rem
        font-size-medium: 0.875rem
        font-size-full: 1rem
        body-font-weight: normal
        body-min-width: 20rem
        container-max-width: 80rem
        header-height: 3.5rem
        menu-width: 16rem
        toc-width: 16rem
        details-colors:
          info: "#6bf"
          warning: "#fd6"
          danger: "#f66"
      calculated_scss:
        border-radius: $padding-small
        mobile-breakpoint: $menu-width + $body-min-width * 1.2 + $toc-width
      light_css:
        gray-100: "#f8f9fa"
        gray-200: "#e9ecef"
        gray-500: "#adb5bd"
        color-link: "#0055bb"
        color-visited-link: "#8440f1"
        body-background: white
        body-font-color: black
        icon-filter: none
      dark_css:
        gray-100: rgba(255, 255, 255, 0.1)
        gray-200: rgba(255, 255, 255, 0.2)
        gray-500: rgba(255, 255, 255, 0.5)
        color-link: "#84b2ff"
        color-visited-link: "#b88dff"
        body-background: "#343a40"
        body-font-color: "#e9ecef"
        icon-filter: brightness(0) invert(1)
      custom_css:
    styles:
      base:
        html:
          enabled: true
        body:
          enabled: true
        headings:
          enabled: true
        links:
          enabled: true
        images:
          enabled: true
        focus:
          enabled: true
        navigation:
          enabled: true
        pagination:
          enabled: true
        containers:
          enabled: true
      platen:
        icon:
          enabled: true
        brand:
          enabled: true
        menu:
          enabled: true
        page:
          enabled: true
        post:
          enabled: true
        header:
          enabled: true
        search:
          enabled: true
        table_of_contents:
          enabled: true
        footer:
          enabled: true
        comments:
          enabled: true
        languages:
          enabled: true
        responsiveness:
          enabled: true
      mobile:
        header:
          enabled: true
        menu:
          enabled: true
        table_of_contents:
          enabled: true
      wide:
        padding:
          enabled: true
      markdown:
        page:
          enabled: true
        headings:
          enabled: true
        links:
          enabled: true
        bold:
          enabled: true
        paragraphs:
          enabled: true
        images:
          enabled: true
        code:
          enabled: true
        blockquotes:
          enabled: true
        tables:
          enabled: true
        lists:
          enabled: true
        rulers:
          enabled: true
        figure:
          enabled: true
        inner:
          enabled: true
      utils:
        basic:
          enabled: true
        toggle:
          enabled: true
        clearfix:
          enabled: true
        spin:
          enabled: true
        fixed:
          enabled: true
        outline:
          enabled: true
    fonts:
      styles:
        - import_name: roboto
      settings:
        body:
          selector: body
          family: "'Roboto', sans-serif"
        code:
          selector: code
          family: "'Roboto Mono', monospace"
    printing:
      styles:
        basic:
          enabled: true
  display:
    table_of_contents:
      minimum_level: 2
      maximum_level: 4
      render: true
    date_format: "January 2, 2006"             # BookDateFormat
    header:
      title_as_heading: false
    menu_root_section: /                        # BookSection
  features:
    search:                                   # booksearch
      enabled: true
      partials:
        header: platen/features/search/header
    comments:                                 # bookcomments
      enabled: false
    pwa:                                      # bookserviceworker
      enabled: true
      partials:
        header: platen/features/pwa/header
    portable_links:                            # BookPortableLinks
      enabled: true
    sharing:
      enabled: true
      partials:
        menu:  platen/features/sharing/menu/render
      menu_text: Share to...
      options:
        blogger:
          href_prefix: https://www.blogger.com/blog-this.g
          text_key: t
          url_key: u
        evernote:
          href_prefix: https://www.evernote.com/clip.action
          text_key: title
          url_key: url
        facebook:
          href_prefix: https://www.facebook.com/sharer/sharer.php
          text_key: quote
          url_key: u
          by_default: true
        hackernews:
          href_prefix: https://news.ycombinator.com/submitlink
          text_key: t
          url_key: u
        linkedin:
          href_prefix: https://www.linkedin.com/sharing/share-offsite/
          text_key: UNSUPPORTED
          url_key: url
        livejournal:
          href_prefix: http://www.livejournal.com/update.bml
          text_key: subject
          url_key: event
        pinterest:
          href_prefix: https://pinterest.com/pin/create/button/
          text_key: description
          url_key: url
        reddit:
          href_prefix: https://www.reddit.com/submit?
          text_key: title
          url_key: url
          by_default: true
        telegram:
          href_prefix: https://t.me/share/url
          text_key: text
          url_key: url
        tumblr:
          href_prefix: https://www.tumblr.com/widgets/share/tool
          text_key: caption
          url_key: canonicalUrl
          by_default: true
        twitter:
          href_prefix: https://twitter.com/intent/tweet
          text_key: text
          url_key: url
          by_default: true
  markup:
    art:
      enabled: true
      partials:
        renderers:
          image: platen/markup/art/image
      style: art
    buttons:
      enabled: true
      partials:
        renderers:
          image: platen/markup/buttons/image
      style: buttons
    code_snippets:
      enabled: true
      partials:
        renderers:
          image: platen/markup/code_snippets/image
    columns:
      enabled: true
      partials:
        renderers:
          codeblock: platen/markup/columns/codeblock
      style: columns
    details:
      enabled: true
      partials:
        renderers:
          codeblock: platen/markup/details/codeblock
      style: details
    # icons:
    #   enabled: true
    #   partials:
    #     header: platen/markup/header/icons
    #     renderers:
    #       image: platen/markup/icons/image
    #   sources:
    #     font_awesome:
    #       enabled: true
    #       partials:
    #         header: platen/markup/icons/fa/header
    #         renderers:
    #           image: platen/markup/icons/fa/image
    itch:
      enabled: true
      partials:
        renderers:
          image: platen/markup/itch/image
    katex:
      enabled:     true
      always_load: false
      version:     0.16.4
      partials:
        header: platen/markup/katex/header
        renderers:
          codeblock: platen/markup/katex/codeblock
          image: platen/markup/katex/image
    key_combos:
      enabled: true
      partials:
        renderers:
          image: platen/markup/key_combos/image
    mermaid:
      enabled: true
      version: 9.3.0
      container: pre
      partials:
        header: platen/markup/mermaid/header
        renderers:
          codeblock: platen/markup/mermaid/codeblock
    section:
      enabled: true
      partials:
        renderers:
          codeblock: platen/markup/section/codeblock
      style: section
    tabs:
      enabled: true
      partials:
        renderers:
          codeblock: platen/markup/tabs/codeblock
      style: tabs
  repository:
    commit_path: commit                        # BookCommitPath
    edit_path: edit/main                       # BookEditPath
  multilingual:                               # BookTranslatedOnly
    translated_only: false
